# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'
use_frameworks!


target 'Axiom Simon Says' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for Axiom Simon Says

  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
end
